#lang racket
(require rackunit
         cpsc411/langs/v6
         cpsc411/compiler-lib
         "../patch-instructions.rkt")

(define (check-input p)
  (if (para-asm-lang-v6? p)
      p
      (error (~a (pretty-format p) "\n is not a semantically valid " "para-asm-lang-v6" " program"))))

(define (check-output p)
  (if (paren-x64-v6? p)
      p
      (error (~a (pretty-format p) "\n is not a semantically valid " "paren-x64-v6" " program"))))

(define-syntax-rule (check-by-interp p)
  (check-equal? (interp-paren-x64-v6 (check-output (patch-instructions p)))
                (interp-para-asm-lang-v6 (check-input p))))


;; Manully added by Trevor on March 10th to cover (set! addr (binop addr opand)) cases

(check-by-interp '(begin
                    (set! (rbp - 0) 10)
                    (set! (rbp - 0) (+ (rbp - 0) -9223372036854775808))))

(check-by-interp '(begin
                    (set! (rbp - 8) 2)
                    (set! (rbp - 8) (- (rbp - 8) 3))))

(check-by-interp '(begin
                    (set! (rbp - 16) -14)
                    (set! (rbp - 16) (* (rbp - 16) 3))))
(check-by-interp '(begin
                    (set! (rbp - 0) 5)
                    (set! (rbp - 16) -14)
                    (set! (rbp - 16) (* (rbp - 16) (rbp - 0)))
                    (set! (rbp - 0) (- (rbp - 0) (rbp - 0)))
                    (set! (rbp - 0) (+ (rbp - 0) (rbp - 16)))
                    (set! rbx -2)
                    (set! (rbp - 16) (+ (rbp - 16) rbx))
                    (set! rbx (+ rbx 1))
                    (set! (rbp - 16) (- (rbp - 16) rbx))
                    (set! rbx (+ rbx 7))
                    (set! (rbp - 16) (* (rbp - 16) rbx))))
;;

;; Manually created by Trevor on March 10th to address (set! addr label), (jump-if relop addr),
;; (jump addr) cases
(check-by-interp '(begin
                    (set! rsp 3)
                    (with-label L.__main.4 (set! rsp (- rsp 1)))
                    (set! (rbp - 8) L.__main.4)
                    (compare rsp 0)
                    (jump-if = done)
                    (jump (rbp - 8))))

(check-by-interp '(begin
                    (set! rsp 3)
                    (set! (rbp - 0) done)
                    (with-label L.__main.4 (set! rsp (- rsp 1)))
                    (set! (rbp - 8) L.__main.4)
                    (compare rsp 0)
                    (jump-if = (rbp - 0))
                    (jump (rbp - 8))))
;;
;; !!! Added by Trevor on March 2nd 2026

(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 0))
                    (jump L.__nested.2)
                    (with-label L.proc.0.1 (set! r15 rdi))
                    (set! r14 -818241658)
                    (set! r14 r14)
                    (set! r13 -1769976594)
                    (set! r13 (* r13 r14))
                    (set! r14 r13)
                    (compare r15 r15)
                    (jump-if != L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.5 (set! rax 1))
                    (jump done)
                    (with-label L.__nested.6 (set! rax r15))
                    (jump done)
                    (with-label L.__nested.2 (set! rax 1764584349))
                    (jump done)
                    (with-label L.__nested.3 (set! rax -9223372036854775808))
                    (jump done)))

;; !!!
;;; Added by Trevor on March 10th (made on March 8th), multiple let bindings allowed

(check-by-interp '(begin
                    (with-label L.__main.10 (set! r15 r15))
                    (set! r14 9223372036854775807)
                    (jump L.tmp.9)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r14 r8)
                    (set! r14 r9)
                    (set! r14 (rbp - 0))
                    (set! r15 r15)
                    (jump L.tmp.1.2)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! rsi 0)
                    (set! rdi 0)
                    (set! r15 r15)
                    (jump L.proc.2.3)
                    (with-label L.proc.2.3 (set! r15 r15))
                    (set! r13 rdi)
                    (set! r14 rsi)
                    (set! (rbp - 0) 1635273112)
                    (set! r9 r13)
                    (set! r8 r14)
                    (set! rcx r13)
                    (set! rdx 445965252)
                    (set! rsi r13)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.proc.0.1)
                    (with-label L.tmp.8 (set! r14 692968731))
                    (jump L.__nested.5)
                    (with-label L.tmp.9 (set! r14 -1490931083))
                    (jump L.__nested.4)
                    (with-label L.__nested.6 (set! rax 0))
                    (jump r15)
                    (with-label L.__nested.7 (set! rax 1843455920))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 1275113131))
                    (jump r15)
                    (with-label L.__nested.5 (set! r14 -1702177019))
                    (jump L.__nested.7)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! r14 9223372036854775807)
                    (set! r14 9223372036854775807)
                    (set! r13 9223372036854775807)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! rdi rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! r9 (rbp - 0))
                    (set! (rbp - 0) r13)
                    (set! r9 rdi)
                    (set! r8 rdi)
                    (set! rcx 9223372036854775807)
                    (set! rdx r14)
                    (set! rsi -9223372036854775808)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.fn.0.1)))
(check-by-interp '(begin
                    (with-label L.__main.6 (set! r15 r15))
                    (set! r14 9223372036854775807)
                    (jump L.__nested.5)
                    (with-label L.func.0.1 (set! (rbp - 0) r15))
                    (set! r14 rdi)
                    (set! r15 rsi)
                    (set! r15 rdx)
                    (set! r13 rcx)
                    (set! (rbp - 8) r8)
                    (set! r14 r14)
                    (set! rbp (- rbp 16))
                    (set! rdx -1140169546)
                    (set! rsi r13)
                    (set! rdi r15)
                    (set! r15 L.rp.3)
                    (jump L.func.1.2)
                    (with-label L.rp.3 (set! rbp (+ rbp 16)))
                    (set! r15 rax)
                    (set! r14 (rbp - 8))
                    (set! r14 (+ r14 r15))
                    (set! rax r14)
                    (jump (rbp - 0))
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r8 rdx)
                    (set! r9 9223372036854775807)
                    (jump L.__nested.7)
                    (with-label L.__nested.7 (set! rdx r8))
                    (set! rsi r8)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.func.1.2)
                    (with-label L.__nested.8 (set! r14 -9223372036854775808))
                    (set! r14 (+ r14 r13))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.4 (set! rax -877748660))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax -9223372036854775808))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 -1640821439)
                    (set! r14 (+ r14 -406700566))
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r14 -477286222)
                    (set! r14 0)
                    (set! rax 643069821)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 r14)
                    (set! r8 r13)
                    (set! rcx -9223372036854775808)
                    (set! rdx r13)
                    (set! rsi r14)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.x.1.2)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! r9 r14)
                    (set! r8 1)
                    (set! rcx -984231193)
                    (set! rdx r13)
                    (set! rsi r13)
                    (set! rdi 933807622)
                    (set! r15 r15)
                    (jump L.x.1.2)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 9223372036854775807)
                    (set! r14 (+ r14 -9223372036854775808))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (compare r14 r14)
                    (jump-if != L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.6 (set! rdi 2058053814))
                    (set! r15 r15)
                    (jump L.func.0.1)
                    (with-label L.__nested.7 (set! r13 r14))
                    (set! r13 (- r13 r14))
                    (set! r13 r13)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r13 r14)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.x.2.3)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.x.2.3)
                    (with-label L.x.2.3 (set! (rbp - 0) r15))
                    (set! r15 rdi)
                    (set! rbp (- rbp 8))
                    (set! rdx -1942673900)
                    (set! rsi r15)
                    (set! rdi r15)
                    (set! r15 L.rp.4)
                    (jump L.tmp.1.2)
                    (with-label L.__nested.8 (set! rdx -1386061378))
                    (set! rsi r15)
                    (set! rdi r15)
                    (set! r15 (rbp - 0))
                    (jump L.tmp.1.2)
                    (with-label L.__nested.9 (set! rdi r15))
                    (set! r15 (rbp - 0))
                    (jump L.func.0.1)
                    (with-label L.rp.4 (set! rbp (+ rbp 8)))
                    (set! r15 rax)
                    (set! r15 r15)
                    (set! r15 r15)
                    (set! r15 r15)
                    (compare r15 r15)
                    (jump-if = L.__nested.8)
                    (jump L.__nested.9)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r14 1)
                    (jump L.__nested.2)
                    (with-label L.__nested.1 (set! rax 2012039291))
                    (jump r15)
                    (with-label L.__nested.2 (set! rax 9223372036854775807))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! rcx 9223372036854775807)
                    (set! rdx -1735352110)
                    (set! rsi 9223372036854775807)
                    (set! rdi 0)
                    (set! r15 r15)
                    (jump L.func.2.3)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! rdi rcx)
                    (set! r8 r8)
                    (set! r9 r9)
                    (set! r14 r14)
                    (set! r14 (- r14 r13))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.proc.1.2 (set! (rbp - 0) r15))
                    (set! r15 9223372036854775807)
                    (set! r15 (+ r15 1))
                    (set! (rbp - 8) r15)
                    (set! rbp (- rbp 16))
                    (set! r9 (rbp - -8))
                    (set! r8 (rbp - -8))
                    (set! rcx (rbp - -8))
                    (set! rdx (rbp - -8))
                    (set! rsi (rbp - -8))
                    (set! rdi 0)
                    (set! r15 L.rp.4)
                    (jump L.func.0.1)
                    (with-label L.rp.4 (set! rbp (+ rbp 16)))
                    (set! r15 rax)
                    (set! r14 (rbp - 8))
                    (compare (rbp - 8) (rbp - 8))
                    (jump-if >= L.tmp.6)
                    (jump L.tmp.7)
                    (with-label L.tmp.6 (set! r14 (rbp - 8)))
                    (jump L.tmp.8)
                    (with-label L.tmp.7 (set! r14 (rbp - 8)))
                    (jump L.tmp.8)
                    (with-label L.tmp.8 (set! r15 r15))
                    (set! r15 r15)
                    (set! r15 -9223372036854775808)
                    (set! rax 9223372036854775807)
                    (jump (rbp - 0))
                    (with-label L.func.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 rdx)
                    (set! r9 rcx)
                    (set! r13 r13)
                    (set! r9 r9)
                    (set! r9 r9)
                    (set! r8 r13)
                    (compare r13 r9)
                    (jump-if >= L.__nested.9)
                    (jump L.__nested.10)
                    (with-label L.__nested.9 (set! rax r13))
                    (jump r15)
                    (with-label L.__nested.10 (set! rax r14))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.6 (set! r15 r15))
                    (set! r14 -9223372036854775808)
                    (jump L.__nested.5)
                    (with-label L.x.0.1 (set! (rbp - 8) r15))
                    (set! r15 rdi)
                    (set! (rbp - 24) rsi)
                    (set! r14 rdx)
                    (set! (rbp - 32) rcx)
                    (set! (rbp - 16) r8)
                    (set! r13 r9)
                    (set! r14 (rbp - 0))
                    (set! rbp (- rbp 40))
                    (set! (rbp - 0) r13)
                    (set! r9 r15)
                    (set! r8 r13)
                    (set! rcx 0)
                    (set! rdx r14)
                    (set! rsi (rbp - -8))
                    (set! rdi (rbp - -8))
                    (set! r15 L.rp.3)
                    (jump L.fn.1.2)
                    (with-label L.__nested.9 (set! rax (rbp - 32)))
                    (jump (rbp - 8))
                    (with-label L.__nested.10 (set! rax (rbp - 24)))
                    (jump (rbp - 8))
                    (with-label L.__nested.7 (set! r14 (rbp - 16)))
                    (set! r14 (+ r14 r15))
                    (set! rax r14)
                    (jump (rbp - 8))
                    (with-label L.__nested.8 (compare (rbp - 32) 0))
                    (jump-if <= L.__nested.9)
                    (jump L.__nested.10)
                    (with-label L.rp.3 (set! rbp (+ rbp 40)))
                    (set! r15 rax)
                    (set! r14 0)
                    (jump L.__nested.7)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r8 r8)
                    (set! r8 r9)
                    (set! r9 (rbp - 0))
                    (set! (rbp - 0) 0)
                    (set! r9 r14)
                    (set! r8 r8)
                    (set! rcx -9223372036854775808)
                    (set! rdx r14)
                    (set! rsi r8)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.fn.1.2)
                    (with-label L.__nested.4 (set! rax -9223372036854775808))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 0))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 9223372036854775807)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! r15 r15))
                    (set! r14 -9223372036854775808)
                    (set! r13 9223372036854775807)
                    (set! r13 9223372036854775807)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! rdi rcx)
                    (set! r13 r8)
                    (set! r9 r9)
                    (set! r9 rdi)
                    (set! r8 r14)
                    (set! rcx -635532414)
                    (set! rdx r13)
                    (set! rsi r13)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.proc.0.1)
                    (with-label L.tmp.1.2 (set! (rbp - 8) r15))
                    (set! (rbp - 24) rdi)
                    (set! (rbp - 0) rsi)
                    (set! (rbp - 32) rdx)
                    (set! (rbp - 40) rcx)
                    (set! (rbp - 16) r8)
                    (set! rbp (- rbp 56))
                    (set! r8 (rbp - -40))
                    (set! rcx (rbp - -16))
                    (set! rdx (rbp - -32))
                    (set! rsi (rbp - -40))
                    (set! rdi (rbp - -16))
                    (set! r15 L.rp.4)
                    (jump L.tmp.1.2)
                    (with-label L.rp.4 (set! rbp (+ rbp 56)))
                    (set! (rbp - 48) rax)
                    (set! rbp (- rbp 56))
                    (set! (rbp - 0) (rbp - -40))
                    (set! r9 (rbp - -24))
                    (set! r8 (rbp - -16))
                    (set! rcx -501684781)
                    (set! rdx (rbp - -40))
                    (set! rsi 9223372036854775807)
                    (set! rdi (rbp - -56))
                    (set! r15 L.rp.5)
                    (jump L.func.2.3)
                    (with-label L.rp.5 (set! rbp (+ rbp 56)))
                    (set! r15 rax)
                    (set! r15 (rbp - 0))
                    (set! rbp (- rbp 56))
                    (set! (rbp - 0) (rbp - -32))
                    (set! r9 (rbp - -56))
                    (set! r8 (rbp - -24))
                    (set! rcx -9223372036854775808)
                    (set! rdx (rbp - -40))
                    (set! rsi 1644735104)
                    (set! rdi (rbp - -32))
                    (set! r15 L.rp.6)
                    (jump L.func.2.3)
                    (with-label L.rp.6 (set! rbp (+ rbp 56)))
                    (set! r15 rax)
                    (set! r14 (rbp - 48))
                    (set! r14 (- r14 (rbp - 48)))
                    (set! r14 r14)
                    (compare (rbp - 48) r15)
                    (jump-if = L.tmp.8)
                    (jump L.tmp.9)
                    (with-label L.tmp.8 (set! r14 r15))
                    (jump L.tmp.10)
                    (with-label L.tmp.9 (set! r14 (rbp - 48)))
                    (jump L.tmp.10)
                    (with-label L.tmp.10 (set! (rbp - 0) r15))
                    (set! r9 -9223372036854775808)
                    (set! r8 (rbp - 24))
                    (set! rcx r14)
                    (set! rdx (rbp - 16))
                    (set! rsi (rbp - 16))
                    (set! rdi r15)
                    (set! r15 (rbp - 8))
                    (jump L.func.2.3)
                    (with-label L.func.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r13 rcx)
                    (set! r14 r8)
                    (set! r9 r9)
                    (set! r8 (rbp - 0))
                    (set! (rbp - 0) 9223372036854775807)
                    (set! r9 r13)
                    (set! r8 r8)
                    (set! rcx r8)
                    (set! rdx r13)
                    (set! rsi -9223372036854775808)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.func.2.3)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! r15 r15))
                    (set! r14 405359082)
                    (set! r13 -915730633)
                    (jump L.tmp.4)
                    (with-label L.func.0.1 (set! (rbp - 0) r15))
                    (set! r15 rdi)
                    (set! (rbp - 16) rsi)
                    (set! (rbp - 24) rdx)
                    (set! (rbp - 32) rcx)
                    (set! (rbp - 8) r8)
                    (set! r14 (rbp - 24))
                    (compare (rbp - 32) (rbp - 8))
                    (jump-if <= L.tmp.10)
                    (jump L.tmp.11)
                    (with-label L.tmp.10 (set! r14 (rbp - 32)))
                    (jump L.tmp.12)
                    (with-label L.tmp.11 (set! r14 (rbp - 8)))
                    (jump L.tmp.12)
                    (with-label L.tmp.12 (set! rbp (- rbp 40)))
                    (set! r8 (rbp - -32))
                    (set! rcx r15)
                    (set! rdx r15)
                    (set! rsi (rbp - -16))
                    (set! rdi 1)
                    (set! r15 L.rp.3)
                    (jump L.func.0.1)
                    (with-label L.rp.3 (set! rbp (+ rbp 40)))
                    (set! r15 rax)
                    (jump L.__nested.9)
                    (with-label L.__nested.8 (set! r8 0))
                    (set! rcx (rbp - 24))
                    (set! rdx 1603961181)
                    (set! rsi (rbp - 16))
                    (set! rdi (rbp - 8))
                    (set! r15 (rbp - 0))
                    (jump L.func.0.1)
                    (with-label L.__nested.9 (set! r9 (rbp - 32)))
                    (set! r8 (rbp - 8))
                    (set! rcx (rbp - 16))
                    (set! rdx (rbp - 8))
                    (set! rsi -9223372036854775808)
                    (set! rdi (rbp - 16))
                    (set! r15 (rbp - 0))
                    (jump L.fn.1.2)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rdi rsi)
                    (set! rsi rdx)
                    (set! rdx rcx)
                    (set! r13 r8)
                    (set! r9 r9)
                    (compare r13 r14)
                    (jump-if >= L.tmp.17)
                    (jump L.tmp.18)
                    (with-label L.tmp.17 (compare rdi -9223372036854775808))
                    (jump-if > L.__nested.13)
                    (jump L.__nested.14)
                    (with-label L.tmp.18 (compare rsi r13))
                    (jump-if >= L.__nested.13)
                    (jump L.__nested.14)
                    (with-label L.__nested.15 (set! rax rdx))
                    (jump r15)
                    (with-label L.__nested.16 (set! rax rdi))
                    (jump r15)
                    (with-label L.__nested.13 (set! r9 rdx))
                    (set! r9 9223372036854775807)
                    (set! r14 r14)
                    (set! rax r13)
                    (jump r15)
                    (with-label L.__nested.14 (compare r13 r14))
                    (jump-if < L.__nested.15)
                    (jump L.__nested.16)
                    (with-label L.tmp.4 (set! r13 -532660031))
                    (set! r13 -248685178)
                    (jump L.tmp.6)
                    (with-label L.tmp.5 (set! r13 0))
                    (jump L.tmp.6)
                    (with-label L.tmp.6 (set! r9 1254220652))
                    (set! r9 r14)
                    (set! r8 r13)
                    (set! rcx 9223372036854775807)
                    (set! rdx r13)
                    (set! rsi r13)
                    (set! rdi -9223372036854775808)
                    (set! r15 r15)
                    (jump L.fn.1.2)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 0)
                    (set! r13 1029279872)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! r8 1)
                    (set! rcx -1754605622)
                    (set! rdx -675715652)
                    (set! rsi r14)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.proc.0.1)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r8 r13)
                    (set! rcx r13)
                    (set! rdx r14)
                    (set! rsi r14)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.proc.0.1)
                    (with-label L.x.2.3 (set! (rbp - 8) r15))
                    (set! (rbp - 32) rdi)
                    (set! r14 rsi)
                    (set! r15 rdx)
                    (set! (rbp - 24) rcx)
                    (set! r13 r8)
                    (set! r9 r9)
                    (set! (rbp - 16) (rbp - 0))
                    (compare (rbp - 24) (rbp - 16))
                    (jump-if >= L.tmp.6)
                    (jump L.tmp.7)
                    (with-label L.rp.4 (set! rbp (+ rbp 40)))
                    (set! r15 rax)
                    (jump L.tmp.8)
                    (with-label L.tmp.6 (set! r15 r14))
                    (jump L.tmp.8)
                    (with-label L.tmp.7 (set! rbp (- rbp 40)))
                    (set! (rbp - 0) 1783645727)
                    (set! r9 r9)
                    (set! r8 (rbp - -16))
                    (set! rcx r13)
                    (set! rdx 0)
                    (set! rsi r15)
                    (set! rdi 1)
                    (set! r15 L.rp.4)
                    (jump L.x.2.3)
                    (with-label L.tmp.8 (set! r15 (rbp - 24)))
                    (set! r15 (* r15 (rbp - 24)))
                    (set! r15 r15)
                    (set! (rbp - 0) (rbp - 24))
                    (set! r9 (rbp - 32))
                    (set! r8 -922337918)
                    (set! rcx (rbp - 16))
                    (set! rdx (rbp - 16))
                    (set! rsi (rbp - 24))
                    (set! rdi (rbp - 16))
                    (set! r15 (rbp - 8))
                    (jump L.x.2.3)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 1)
                    (set! r13 -1606724555)
                    (jump L.tmp.3)
                    (with-label L.tmp.3 (set! r14 1))
                    (set! r13 1)
                    (set! r13 -9223372036854775808)
                    (jump L.__nested.1)
                    (with-label L.tmp.4 (set! r14 -1879829070))
                    (jump L.__nested.1)
                    (with-label L.__nested.1 (set! r14 -634246165))
                    (set! r14 (- r14 -684848771))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.2 (set! rax 0))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r14 0)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! rdx r14)
                    (set! rsi -1803672217)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.proc.1.2)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rdx r13)
                    (set! rsi r14)
                    (set! rdi 1)
                    (set! r15 r15)
                    (jump L.proc.1.2)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 1550347185)
                    (set! r14 9223372036854775807)
                    (set! r13 -9223372036854775808)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r13 9223372036854775807)
                    (set! r13 (- r13 r14))
                    (set! rax r13)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! r15 r15))
                    (set! r14 1)
                    (set! r14 -9223372036854775808)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.proc.0.1 (set! (rbp - 0) r15))
                    (set! (rbp - 24) rdi)
                    (set! (rbp - 16) rsi)
                    (set! (rbp - 8) rdx)
                    (set! rbp (- rbp 56))
                    (set! rdx (rbp - -48))
                    (set! rsi (rbp - -48))
                    (set! rdi 9223372036854775807)
                    (set! r15 L.rp.2)
                    (jump L.proc.0.1)
                    (with-label L.__nested.10 (set! rax (rbp - 8)))
                    (jump (rbp - 0))
                    (with-label L.__nested.11 (set! rax r15))
                    (jump (rbp - 0))
                    (with-label L.__nested.8 (compare (rbp - 40) (rbp - 40)))
                    (jump-if >= L.__nested.10)
                    (jump L.__nested.11)
                    (with-label L.__nested.9 (set! r15 -2087609688))
                    (set! r15 (rbp - 40))
                    (set! rax (rbp - 32))
                    (jump (rbp - 0))
                    (with-label L.rp.2 (set! rbp (+ rbp 56)))
                    (set! (rbp - 40) rax)
                    (set! rbp (- rbp 56))
                    (set! rdx (rbp - -32))
                    (set! rsi (rbp - -48))
                    (set! rdi (rbp - -32))
                    (set! r15 L.rp.3)
                    (jump L.proc.0.1)
                    (with-label L.rp.3 (set! rbp (+ rbp 56)))
                    (set! (rbp - 32) rax)
                    (set! rbp (- rbp 56))
                    (set! rdx (rbp - -32))
                    (set! rsi (rbp - -48))
                    (set! rdi (rbp - -48))
                    (set! r15 L.rp.4)
                    (jump L.proc.0.1)
                    (with-label L.rp.4 (set! rbp (+ rbp 56)))
                    (set! (rbp - 24) rax)
                    (set! r15 (rbp - 16))
                    (set! rbp (- rbp 56))
                    (set! rdx (rbp - -40))
                    (set! rsi (rbp - -48))
                    (set! rdi (rbp - -48))
                    (set! r15 L.rp.5)
                    (jump L.proc.0.1)
                    (with-label L.rp.5 (set! rbp (+ rbp 56)))
                    (set! r15 rax)
                    (set! rbp (- rbp 56))
                    (set! rdx (rbp - -32))
                    (set! rsi r15)
                    (set! rdi r15)
                    (set! r15 L.rp.6)
                    (jump L.proc.0.1)
                    (with-label L.rp.6 (set! rbp (+ rbp 56)))
                    (set! r15 rax)
                    (compare r15 (rbp - 8))
                    (jump-if > L.__nested.8)
                    (jump L.__nested.9)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! r14 1)
                    (set! r14 (+ r14 9223372036854775807))
                    (set! r14 r14)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rcx 2099518136)
                    (set! rdx r14)
                    (set! rsi r14)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.func.2.3)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rdi rdx)
                    (set! r13 rcx)
                    (set! r8 r8)
                    (set! r9 r9)
                    (set! r9 9223372036854775807)
                    (set! r9 rdi)
                    (set! r9 (+ r9 r14))
                    (set! r9 r9)
                    (set! r13 r13)
                    (set! r13 (+ r13 r14))
                    (set! r13 r13)
                    (set! r14 r14)
                    (set! rdi 0)
                    (set! r15 r15)
                    (jump L.fn.0.1)
                    (with-label L.func.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r8 rdx)
                    (set! r13 rcx)
                    (set! r9 9223372036854775807)
                    (set! r8 r8)
                    (set! rcx r14)
                    (set! rdx r13)
                    (set! rsi r13)
                    (set! rdi 1)
                    (set! r15 r15)
                    (jump L.tmp.1.2)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 0)
                    (set! r14 1)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r9 -9223372036854775808)
                    (set! r8 0)
                    (set! rcx -9223372036854775808)
                    (set! rdx -9223372036854775808)
                    (set! rsi -2062025435)
                    (set! rdi 0)
                    (set! r15 r15)
                    (jump L.x.1.2)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r9 0)
                    (set! r8 1)
                    (set! rcx 9223372036854775807)
                    (set! rdx 9223372036854775807)
                    (set! rsi 1)
                    (set! rdi 38797657)
                    (set! r15 r15)
                    (jump L.x.1.2)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! rdi rcx)
                    (set! rsi r8)
                    (set! r8 r9)
                    (compare rsi rsi)
                    (jump-if >= L.tmp.6)
                    (jump L.tmp.7)
                    (with-label L.tmp.6 (compare r14 rdi))
                    (jump-if < L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.tmp.7 (compare r8 812242710))
                    (jump-if < L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.__nested.4 (set! r14 rsi))
                    (set! r14 (- r14 rdi))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.5 (set! r15 r15))
                    (jump L.func.0.1)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! rax 1)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! r9 rcx)
                    (set! rdx r13)
                    (set! rsi -9223372036854775808)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.proc.1.2)
                    (with-label L.proc.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r14 r14)
                    (set! r14 (- r14 r13))
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 -550916464)
                    (set! r14 9223372036854775807)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 9223372036854775807)
                    (set! r14 (- r14 1))
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! r15 r15))
                    (set! r14 9223372036854775807)
                    (jump L.__nested.5)
                    (with-label L.tmp.0.1 (set! (rbp - 0) r15))
                    (set! (rbp - 16) rdi)
                    (set! (rbp - 8) rsi)
                    (set! r15 rdx)
                    (set! (rbp - 24) rcx)
                    (set! rbp (- rbp 32))
                    (set! rcx (rbp - -16))
                    (set! rdx (rbp - -8))
                    (set! rsi (rbp - -24))
                    (set! rdi (rbp - -24))
                    (set! r15 L.rp.3)
                    (jump L.tmp.0.1)
                    (with-label L.rp.3 (set! rbp (+ rbp 32)))
                    (set! r15 rax)
                    (set! r15 (rbp - 8))
                    (set! r15 (- r15 (rbp - 24)))
                    (set! r15 r15)
                    (set! r15 (rbp - 8))
                    (set! r15 1)
                    (set! r15 (rbp - 24))
                    (set! r15 (rbp - 16))
                    (set! rbp (- rbp 32))
                    (set! rdx (rbp - -16))
                    (set! rsi 9223372036854775807)
                    (set! rdi (rbp - -8))
                    (set! r15 L.rp.4)
                    (jump L.x.1.2)
                    (with-label L.rp.4 (set! rbp (+ rbp 32)))
                    (set! r15 rax)
                    (set! rdx (rbp - 8))
                    (set! rsi (rbp - 8))
                    (set! rdi -9223372036854775808)
                    (set! r15 (rbp - 0))
                    (jump L.x.1.2)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r9 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rdx r13)
                    (set! rsi 580696126)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.x.1.2)
                    (with-label L.__nested.5 (set! rax -1677147892))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 874915829))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.8 (set! r15 r15))
                    (set! r14 -534391580)
                    (jump L.__nested.6)
                    (with-label L.proc.0.1 (set! (rbp - 8) r15))
                    (set! (rbp - 40) rdi)
                    (set! (rbp - 24) rsi)
                    (set! (rbp - 48) rdx)
                    (set! r15 rcx)
                    (set! (rbp - 32) r8)
                    (set! (rbp - 16) r9)
                    (set! (rbp - 0) (rbp - 0))
                    (compare (rbp - 0) -727829088)
                    (jump-if > L.__nested.10)
                    (jump L.__nested.9)
                    (with-label L.rp.4 (set! rbp (+ rbp 56)))
                    (set! r15 rax)
                    (set! rbp (- rbp 56))
                    (set! r9 (rbp - -56))
                    (set! r8 -9223372036854775808)
                    (set! rcx (rbp - -24))
                    (set! rdx 1)
                    (set! rsi (rbp - -16))
                    (set! rdi (rbp - -8))
                    (set! r15 L.rp.5)
                    (jump L.fn.1.2)
                    (with-label L.rp.5 (set! rbp (+ rbp 56)))
                    (set! r15 rax)
                    (set! r15 (rbp - 24))
                    (set! rax (rbp - 16))
                    (jump (rbp - 8))
                    (with-label L.__nested.9 (set! r14 (rbp - 40)))
                    (set! rbp (- rbp 56))
                    (set! (rbp - 0) (rbp - -16))
                    (set! r9 (rbp - -16))
                    (set! r8 r15)
                    (set! rcx (rbp - -32))
                    (set! rdx (rbp - -8))
                    (set! rsi (rbp - -24))
                    (set! rdi (rbp - -32))
                    (set! r15 L.rp.4)
                    (jump L.proc.0.1)
                    (with-label L.__nested.10 (set! rax -774243080))
                    (jump (rbp - 8))
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! rdi rdi)
                    (set! r14 rsi)
                    (set! rsi rdx)
                    (set! rbx rcx)
                    (set! r13 r8)
                    (set! r8 r9)
                    (compare r13 rdi)
                    (jump-if < L.tmp.15)
                    (jump L.tmp.16)
                    (with-label L.tmp.15 (compare rdi rbx))
                    (jump-if >= L.tmp.13)
                    (jump L.tmp.14)
                    (with-label L.tmp.16 (compare r14 r14))
                    (jump-if != L.tmp.13)
                    (jump L.tmp.14)
                    (with-label L.tmp.17 (compare rdi rdi))
                    (jump-if < L.__nested.11)
                    (jump L.__nested.12)
                    (with-label L.tmp.18 (compare rsi r13))
                    (jump-if >= L.__nested.11)
                    (jump L.__nested.12)
                    (with-label L.tmp.13 (compare r8 rbx))
                    (jump-if >= L.tmp.17)
                    (jump L.tmp.18)
                    (with-label L.tmp.14 (compare rbx r8))
                    (jump-if > L.__nested.12)
                    (jump L.__nested.11)
                    (with-label L.__nested.11 (set! r9 -1548357748))
                    (set! r9 (- r9 r13))
                    (set! r13 r9)
                    (set! r9 r13)
                    (set! r8 rsi)
                    (set! rcx r14)
                    (set! rdx rsi)
                    (set! rsi 0)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.fn.1.2)
                    (with-label L.__nested.12 (set! r9 rdi))
                    (set! r8 r8)
                    (set! rcx r8)
                    (set! rdx r14)
                    (set! rsi r13)
                    (set! rdi rbx)
                    (set! r15 r15)
                    (jump L.fn.2.3)
                    (with-label L.fn.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r13 rcx)
                    (set! r14 r8)
                    (set! r9 r9)
                    (set! r9 0)
                    (set! r8 1)
                    (set! rcx r14)
                    (set! rdx r13)
                    (set! rsi -9223372036854775808)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.fn.2.3)
                    (with-label L.__nested.6 (set! rax 0))
                    (jump r15)
                    (with-label L.__nested.7 (set! rax 0))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 -1762920629)
                    (set! r14 1)
                    (set! r14 9223372036854775807)
                    (set! rax 0)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! r14 1038395452)
                    (jump L.__nested.2)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! rdi rdx)
                    (set! rdi rcx)
                    (set! r8 r8)
                    (set! r9 r9)
                    (set! r9 r13)
                    (set! r8 r13)
                    (set! rcx rdi)
                    (set! rdx r14)
                    (set! rsi 15882253)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.proc.0.1)
                    (with-label L.__nested.2 (set! rax -9223372036854775808))
                    (jump r15)
                    (with-label L.__nested.3 (set! rax 717010255))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! r15 r15))
                    (set! r14 0)
                    (jump L.__nested.1)
                    (with-label L.__nested.3 (set! rax 0))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax 9223372036854775807))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 1))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 9223372036854775807))
                    (jump r15)
                    (with-label L.__nested.1 (set! r14 -9223372036854775808))
                    (jump L.__nested.4)
                    (with-label L.__nested.2 (set! r14 -9223372036854775808))
                    (jump L.__nested.5)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 0)
                    (jump L.__nested.1)
                    (with-label L.__nested.3 (set! rax 0))
                    (jump r15)
                    (with-label L.__nested.4 (set! rax -9223372036854775808))
                    (jump r15)
                    (with-label L.__nested.1 (set! rax 1620518798))
                    (jump r15)
                    (with-label L.__nested.2 (set! r14 0))
                    (jump L.__nested.3)))
(check-by-interp '(begin
                    (with-label L.__main.6 (set! r15 r15))
                    (set! r14 -9223372036854775808)
                    (jump L.__nested.5)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! rdx 9223372036854775807)
                    (set! rsi r14)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.tmp.1.2)
                    (with-label L.tmp.1.2 (set! r15 r15))
                    (set! r13 rdi)
                    (set! r14 rsi)
                    (set! r9 rdx)
                    (set! rdx r13)
                    (set! rsi 9223372036854775807)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.tmp.1.2)
                    (with-label L.tmp.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! rdi rdx)
                    (set! rdi rcx)
                    (set! r8 r8)
                    (set! r9 r9)
                    (set! r9 r13)
                    (set! r8 r8)
                    (set! rcx r14)
                    (set! rdx r8)
                    (set! rsi 1666412948)
                    (set! rdi 273235985)
                    (set! r15 r15)
                    (jump L.tmp.2.3)
                    (with-label L.__nested.4 (set! rax 9223372036854775807))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 1))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rax -167685894)
                    (jump r15)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 rdx)
                    (set! rdi rcx)
                    (set! r9 r8)
                    (set! r8 r14)
                    (set! rcx rdi)
                    (set! rdx r13)
                    (set! rsi r14)
                    (set! rdi r9)
                    (set! r15 r15)
                    (jump L.fn.0.1)))
(check-by-interp '(begin
                    (with-label L.__main.4 (set! r15 r15))
                    (set! r14 1962527269)
                    (set! r14 (+ r14 9223372036854775807))
                    (set! rax r14)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r9 r13)
                    (set! r8 r13)
                    (set! rcx r14)
                    (set! rdx r13)
                    (set! rsi r14)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.fn.2.3)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rdi rsi)
                    (set! r13 rdx)
                    (set! r14 rcx)
                    (set! r9 r8)
                    (set! r9 r9)
                    (set! r8 r13)
                    (set! r8 (- r8 rdi))
                    (set! r8 r8)
                    (set! rdi r9)
                    (set! r8 r8)
                    (set! r13 r13)
                    (set! r14 r14)
                    (set! r8 r9)
                    (set! rcx r14)
                    (set! rdx r9)
                    (set! rsi -9223372036854775808)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.fn.1.2)
                    (with-label L.fn.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r8 r8)
                    (set! r9 r9)
                    (set! rsi r13)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.func.0.1)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rdi 733499244)
                    (set! r15 r15)
                    (jump L.func.0.1)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (compare r14 r14)
                    (jump-if > L.__nested.4)
                    (jump L.__nested.3)
                    (with-label L.__nested.5 (set! rax r14))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax r14))
                    (jump r15)
                    (with-label L.__nested.3 (compare r14 r14))
                    (jump-if = L.__nested.5)
                    (jump L.__nested.6)
                    (with-label L.__nested.4 (set! rdi 9223372036854775807))
                    (set! r15 r15)
                    (jump L.func.0.1)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 1830309714)
                    (set! r13 -9223372036854775808)
                    (set! r13 -9223372036854775808)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.proc.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r8 r14)
                    (set! rcx 1)
                    (set! rdx 0)
                    (set! rsi -9223372036854775808)
                    (set! rdi 835392363)
                    (set! r15 r15)
                    (jump L.fn.1.2)
                    (with-label L.fn.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! r13 rcx)
                    (set! r13 r8)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.x.2.3)
                    (with-label L.x.2.3 (set! (rbp - 0) r15))
                    (set! (rbp - 8) rdi)
                    (set! rbp (- rbp 16))
                    (set! rcx (rbp - -8))
                    (set! rdx (rbp - -8))
                    (set! rsi (rbp - -8))
                    (set! rdi (rbp - -8))
                    (set! r15 L.rp.4)
                    (jump L.proc.0.1)
                    (with-label L.rp.4 (set! rbp (+ rbp 16)))
                    (set! r15 rax)
                    (set! r15 r15)
                    (set! r15 (- r15 r15))
                    (set! r15 r15)
                    (compare r15 (rbp - 8))
                    (jump-if <= L.tmp.6)
                    (jump L.tmp.7)
                    (with-label L.tmp.6 (set! r14 r15))
                    (jump L.tmp.8)
                    (with-label L.tmp.7 (set! r14 (rbp - 8)))
                    (jump L.tmp.8)
                    (with-label L.tmp.8 (set! r15 r15))
                    (set! r14 (rbp - 8))
                    (set! r14 r15)
                    (set! r15 r15)
                    (set! r15 (rbp - 8))
                    (set! rdi r15)
                    (set! r15 (rbp - 0))
                    (jump L.x.2.3)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! rax -575594324)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r13 r8)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.func.1.2 (set! (rbp - 0) r15))
                    (set! r15 -620373304)
                    (set! r15 (- r15 -68719063))
                    (set! r15 r15)
                    (set! (rbp - 8) 0)
                    (set! rbp (- rbp 16))
                    (set! r15 L.rp.4)
                    (jump L.func.1.2)
                    (with-label L.rp.4 (set! rbp (+ rbp 16)))
                    (set! r15 rax)
                    (set! rax (rbp - 8))
                    (jump (rbp - 0))
                    (with-label L.x.2.3 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r15 r15)
                    (jump L.func.1.2)))
(check-by-interp '(begin
                    (with-label L.__main.7 (set! r15 r15))
                    (set! r14 0)
                    (jump L.__nested.3)
                    (with-label L.x.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r14 rdx)
                    (set! r14 rcx)
                    (set! r13 r8)
                    (set! r13 r9)
                    (set! rsi 1)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.x.1.2)
                    (with-label L.x.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r13 rsi)
                    (compare r13 -9223372036854775808)
                    (jump-if <= L.__nested.8)
                    (jump L.__nested.9)
                    (with-label L.__nested.8 (set! r9 r14))
                    (set! r8 r13)
                    (set! rcx r13)
                    (set! rdx r13)
                    (set! rsi r14)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.x.0.1)
                    (with-label L.__nested.9 (set! rax r13))
                    (jump r15)
                    (with-label L.__nested.5 (set! rax 1))
                    (jump r15)
                    (with-label L.__nested.6 (set! rax 1))
                    (jump r15)
                    (with-label L.__nested.3 (set! r14 996590913))
                    (set! r13 299367411)
                    (set! r13 -9223372036854775808)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.4 (set! r14 894536270))
                    (jump L.__nested.6)))
(check-by-interp '(begin
                    (with-label L.__main.8 (set! r15 r15))
                    (set! r14 1973720366)
                    (jump L.__nested.6)
                    (with-label L.tmp.0.1 (set! r15 r15))
                    (set! r13 rdi)
                    (set! rdi rsi)
                    (set! r14 rdx)
                    (set! rbx rcx)
                    (set! r9 r8)
                    (compare rdi 9223372036854775807)
                    (jump-if <= L.__nested.9)
                    (jump L.__nested.10)
                    (with-label L.__nested.9 (set! (rbp - 0) rbx))
                    (set! r9 -9223372036854775808)
                    (set! r8 1)
                    (set! rcx r14)
                    (set! rdx r13)
                    (set! rsi r14)
                    (set! rdi rbx)
                    (set! r15 r15)
                    (jump L.tmp.1.2)
                    (with-label L.__nested.10 (set! r9 r9))
                    (set! r13 r13)
                    (set! r14 r14)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.tmp.1.2 (set! (rbp - 8) r15))
                    (set! r15 rdi)
                    (set! (rbp - 24) rsi)
                    (set! r15 rdx)
                    (set! r14 rcx)
                    (set! (rbp - 40) r8)
                    (set! (rbp - 16) r9)
                    (set! (rbp - 32) (rbp - 0))
                    (set! r13 1242010444)
                    (compare r13 r15)
                    (jump-if > L.tmp.12)
                    (jump L.tmp.11)
                    (with-label L.rp.3 (set! rbp (+ rbp 56)))
                    (set! (rbp - 48) rax)
                    (jump L.tmp.13)
                    (with-label L.rp.4 (set! rbp (+ rbp 56)))
                    (set! (rbp - 48) rax)
                    (jump L.tmp.13)
                    (with-label L.tmp.11 (set! rbp (- rbp 56)))
                    (set! r8 (rbp - -40))
                    (set! rcx 1)
                    (set! rdx r14)
                    (set! rsi (rbp - -40))
                    (set! rdi (rbp - -16))
                    (set! r15 L.rp.3)
                    (jump L.tmp.0.1)
                    (with-label L.tmp.12 (set! rbp (- rbp 56)))
                    (set! r8 r14)
                    (set! rcx r14)
                    (set! rdx (rbp - -32))
                    (set! rsi r15)
                    (set! rdi r15)
                    (set! r15 L.rp.4)
                    (jump L.tmp.0.1)
                    (with-label L.tmp.13 (set! r15 (rbp - 32)))
                    (set! r15 (* r15 (rbp - 24)))
                    (set! r15 r15)
                    (set! rbp (- rbp 56))
                    (set! r8 (rbp - -16))
                    (set! rcx (rbp - -16))
                    (set! rdx 0)
                    (set! rsi (rbp - -32))
                    (set! rdi (rbp - -32))
                    (set! r15 L.rp.5)
                    (jump L.tmp.0.1)
                    (with-label L.rp.5 (set! rbp (+ rbp 56)))
                    (set! r15 rax)
                    (set! (rbp - 0) (rbp - 16))
                    (set! r9 (rbp - 48))
                    (set! r8 (rbp - 32))
                    (set! rcx r15)
                    (set! rdx 1)
                    (set! rsi (rbp - 24))
                    (set! rdi (rbp - 16))
                    (set! r15 (rbp - 8))
                    (jump L.tmp.1.2)
                    (with-label L.__nested.6 (set! rax 9223372036854775807))
                    (jump r15)
                    (with-label L.__nested.7 (set! (rbp - 0) 379193781))
                    (set! r9 726597669)
                    (set! r8 -264137160)
                    (set! rcx -1022801227)
                    (set! rdx 501537014)
                    (set! rsi 9223372036854775807)
                    (set! rdi 9223372036854775807)
                    (set! r15 r15)
                    (jump L.tmp.1.2)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r9 1521957632)
                    (set! r13 -9223372036854775808)
                    (set! r14 -9223372036854775808)
                    (set! rax 0)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 -9223372036854775808)
                    (set! r13 0)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r13 r14)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r13 r13)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 1)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r14 r14)
                    (set! r13 r14)
                    (set! r13 r14)
                    (set! r13 (+ r13 r14))
                    (set! r13 r13)
                    (set! r13 r14)
                    (set! r13 1648274049)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.2 (set! r15 r15))
                    (set! rax 0)
                    (jump r15)
                    (with-label L.func.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! rsi r14)
                    (set! rdi 1)
                    (set! r15 r15)
                    (jump L.func.0.1)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r14 -9223372036854775808)
                    (jump L.__nested.2)
                    (with-label L.__nested.1 (set! rax -9223372036854775808))
                    (jump r15)
                    (with-label L.__nested.2 (set! rax 9223372036854775807))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r9 0)
                    (set! r8 0)
                    (set! rcx 1)
                    (set! rdx 1)
                    (set! rsi -1337458253)
                    (set! rdi 9223372036854775807)
                    (set! r15 r15)
                    (jump L.func.1.2)
                    (with-label L.fn.0.1 (set! r15 r15))
                    (set! r14 rdi)
                    (set! r14 rsi)
                    (set! r13 rdx)
                    (set! rdi rcx)
                    (set! r13 r8)
                    (set! r9 r14)
                    (set! r8 rdi)
                    (set! rcx r13)
                    (set! rdx 1064830001)
                    (set! rsi r14)
                    (set! rdi r13)
                    (set! r15 r15)
                    (jump L.func.1.2)
                    (with-label L.func.1.2 (set! r15 r15))
                    (set! r14 rdi)
                    (set! rsi rsi)
                    (set! rdi rdx)
                    (set! rdx rcx)
                    (set! r8 r8)
                    (set! r13 r9)
                    (compare r8 r8)
                    (jump-if < L.tmp.10)
                    (jump L.tmp.11)
                    (with-label L.tmp.10 (compare r14 r14))
                    (jump-if = L.tmp.8)
                    (jump L.tmp.9)
                    (with-label L.tmp.11 (compare rsi r8))
                    (jump-if != L.tmp.8)
                    (jump L.tmp.9)
                    (with-label L.tmp.12 (set! r9 1))
                    (compare r9 rdx)
                    (jump-if <= L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.tmp.13 (set! r9 529266316))
                    (compare r9 r8)
                    (jump-if >= L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.tmp.8 (compare r13 0))
                    (jump-if = L.__nested.4)
                    (jump L.__nested.5)
                    (with-label L.tmp.9 (set! r9 0))
                    (compare r9 r13)
                    (jump-if > L.tmp.12)
                    (jump L.tmp.13)
                    (with-label L.__nested.6 (set! r14 r13))
                    (set! rax r13)
                    (jump r15)
                    (with-label L.__nested.7 (set! r9 r13))
                    (set! r8 rdi)
                    (set! rcx rsi)
                    (set! rdx rsi)
                    (set! rsi r14)
                    (set! rdi rdi)
                    (set! r15 r15)
                    (jump L.func.1.2)
                    (with-label L.__nested.4 (set! r9 rdi))
                    (compare rdx r9)
                    (jump-if <= L.__nested.6)
                    (jump L.__nested.7)
                    (with-label L.__nested.5 (set! r14 rdi))
                    (set! r14 r14)
                    (set! r9 rdi)
                    (set! r8 r14)
                    (set! rcx rdi)
                    (set! rdx r13)
                    (set! rsi r13)
                    (set! rdi r14)
                    (set! r15 r15)
                    (jump L.func.1.2)))
(check-by-interp '(begin
                    (with-label L.__main.5 (set! r15 r15))
                    (set! r14 9223372036854775807)
                    (jump L.tmp.3)
                    (with-label L.tmp.3 (jump L.__nested.1))
                    (with-label L.tmp.4 (set! r14 9223372036854775807))
                    (jump L.__nested.1)
                    (with-label L.__nested.1 (set! r14 -9223372036854775808))
                    (set! r14 -9223372036854775808)
                    (set! r13 9223372036854775807)
                    (set! r13 (* r13 -9223372036854775808))
                    (set! r13 r13)
                    (set! rax r14)
                    (jump r15)
                    (with-label L.__nested.2 (set! r14 1865158198))
                    (set! r14 (+ r14 1))
                    (set! r14 r14)
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.3 (set! r15 r15))
                    (set! r14 1069510162)
                    (jump L.__nested.1)
                    (with-label L.__nested.1 (set! rax 1))
                    (jump r15)
                    (with-label L.__nested.2 (set! rax 323863587))
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 379335310)
                    (set! r14 (* r14 0))
                    (set! rax r14)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! rax 0)
                    (jump r15)))
(check-by-interp '(begin
                    (with-label L.__main.1 (set! r15 r15))
                    (set! r14 -9223372036854775808)
                    (set! r14 (- r14 0))
                    (set! r13 r14)
                    (set! r14 -9223372036854775808)
                    (set! r9 1969620648)
                    (set! r13 r13)
                    (set! r14 r14)
                    (set! rax r13)
                    (jump r15)))

;;;
